## Generated by dust2 (version 0.3.24) - do not edit
sirode <- structure(
  function() get("sirode"),
  class = "dust_system_generator",
  name = "sirode",
  package = "trydustevents",
  path = NULL,
  parameters = data.frame(
    name = c("I0", "N", "beta", "gamma", "nu", "infect_cap", "event_time_on", "event_time_off"),
    type = c("real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type"),
    constant = c(TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE)),
  properties = list(
    time_type = "continuous",
    has_compare = FALSE,
    has_adjoint = FALSE),
  default_dt = NULL)
